apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tic-tac-toe-network-policy
  namespace: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  podSelector:
    matchLabels:
      app: tic-tac-toe
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 443
