apiVersion: v1
kind: ServiceAccount
metadata:
  name: tic-tac-toe
  namespace: tic-tac-toe
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: tic-tac-toe
automountServiceAccountToken: false
